# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are building a GitHub project page then use these settings:
# url: "http://anguskk.github.io/hackuestc"
# baseurl: "/hackuestc"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Angus

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Angus

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-135646126-1"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# --- Misc --- #

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"

highlighter: rouge



# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
